### ISSUE TITLE
How do you guys use this?

### ISSUE THREAD

**Issue by KyleGobel** [NFig/NFig#2]
Hey, I'm just wondering in practice how you typically setup your apps to use this, is the configuration part (setting and overriding various settings) always connected to the app itself?

What I was thinking was that I could set up my default settings in my app and they would get synced to redis.  I could then have a seperate config website or something where I could change my settings for various apps running in the wild (without having to know what machine the app is running on).

I have my default settings, and I'm able to override them from redis, but it appears there's no way to sync the existing settings or defaults to redis...making it hard to know what settings I can override externally.  Do you build a GUI for settings for every app you use this in?

**Comment by bretcope** [comment]
Great questions.

We use NFig.UI (looks like you've already discovered it) which is a React plugin that provides most of the functionality we need for a GUI in each app. There's a little bit of scaffolding required per app, but it's fairly minimal and necessary for integrating into the app's authentication story anyway.

As for centralized settings for multiple apps, that's not supported for several reasons:
- We believe defaults should be in code. That's the best place for them because it keeps them very near the code that uses the settings.
- We want to keep things simple. Keeping defaults in Redis, or having more than one way overrides can be set, would increase complexity. We've _literally never_ had a bug in NFig or NFig.Redis, and that is largely due to its simplicity. I'm not keen on increasing the complexity (and increasing risk) without very strong reasons.
- There is validation that takes place for overrides. For example, to validate that an integer is entered for an integer setting; although there can be custom validation as well. This validation occurs in the application where the settings are declared, and hence would be difficult to impossible to validate elsewhere.

Of course one downside is that if an override is causing an app to not startup, that means you also can't get to the interface to clear that override. It's not something we've actually had happen in practice, but if it did, we would probably just clear it manually in Redis. It's possible that a centralized system could be built to clear overrides. On the other hand, a command-line interface would work just as well.

All of that being said, if you want to build something for yourself that does the things you want, and even use NFig as the basis for it, there's nothing stopping you. It's simply saying I don't think it's something we'd be interested in officially supporting.

**Comment by KyleGobel** [comment]
Thanks much for the thorough answer, that makes sense.  

Where I'm at we have a lot of smallish topshelf windows services and several don't have any real GUI.

I didn't really want to put a self hosting web server in each of these, but it turned out actually really easy and was able to abstract away most of the setup into a nice nuget package.  I was surprised in the ease of using the NFig.UI and that react component, hats off to @rossipedia for that, and yourself for NFig.

**Comment by bretcope** [comment]
Great. I'm glad to hear it, and thank you. We're still going to work on some documentation in the near future, but let us know if you need any help in the meantime.
